### ISSUE TITLE
Plugin can't loading Vault data

### ISSUE THREAD

**Issue by Yamilel** [Foxxite/MultiCharacter#9]
Hi when I  try to create a new character i get an error in my consol saying this:
[com.foxxite.multicharacter.MultiCharacter] [MultiCharacter] A fatal error occurred while loading Vault data. Is Vault installed?
Vault is on my server installed and the other plugins work fine with it.
I also get this in the consol:
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register com.foxxite.multicharacter.worldspacemenu.WorldSpaceMenu@5cedf2dc while not enabled
	at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:653) ~[patched_1.16.5.jar:git-Paper-788]
	at com.foxxite.multicharacter.worldspacemenu.WorldSpaceMenu.<init>(WorldSpaceMenu.java:145) ~[?:?]
	at com.foxxite.multicharacter.character.creator.CharacterCreator$1.run(CharacterCreator.java:135) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-788]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:485) ~[patched_1.16.5.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1427) ~[patched_1.16.5.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-788]
	at java.lang.Thread.run(Thread.java:829) [?:?]
 I tryed the plugin on Paper and Spigot server but on bouth servers i had the same resoult.

**Comment by Yamilel** [comment]
Never mind im stupid sorry
